from __future__ import annotations

from typing import Final

PAIRLIST_SCRIPT: Final = (
    "<script>\n"
    "const pairlistBlacklist = document.querySelector('[data-testid=\"pairlist-blacklist\"]');\n"
    "const pairlistPreview = document.querySelector('[data-testid=\"pairlist-preview-state\"]');\n"
    "const pairlistAudit = document.querySelector('[data-testid=\"pairlist-audit-log\"]');\n"
    "async function postPairlist(path) {\n"
    "  const response = await fetch(path, {\n"
    "    method: 'POST',\n"
    "    headers: {'content-type': 'application/json', ...csrfHeaders()},\n"
    "    body: JSON.stringify({blacklist: pairlistBlacklist.value})\n"
    "  });\n"
    "  return response.json();\n"
    "}\n"
    "function pairlistSummary(payload) {\n"
    "  const rejected = payload.rejected_pairs.map((item) => "
    "`${item.pair}: ${item.reasons.join(',')}`);\n"
    "  const none = msg('common.none', 'none');\n"
    "  const pairNames = payload.accepted_pairs.join(',') || none;\n"
    "  const accepted = msg('pairlist.accepted', 'accepted={pairs}')"
    ".replace('{pairs}', pairNames);\n"
    "  return [accepted, ...rejected].join('\\n');\n"
    "}\n"
    "const pairlistPreviewButton = document.querySelector("
    "'[data-testid=\"pairlist-preview-button\"]');\n"
    "const pairlistDraftButton = document.querySelector("
    "'[data-testid=\"pairlist-save-draft-button\"]');\n"
    "const pairlistApplyButton = document.querySelector("
    "'[data-testid=\"pairlist-apply-button\"]');\n"
    "if (pairlistBlacklist) {\n"
    "  pairlistPreviewButton.onclick = async () => {\n"
    "    const payload = await postPairlist('/api/v1/pairlist/preview');\n"
    "    pairlistPreview.textContent = pairlistSummary(payload);\n"
    "  };\n"
    "  pairlistDraftButton.onclick = async () => {\n"
    "    const payload = await postPairlist('/api/v1/pairlist/draft');\n"
    "    pairlistPreview.textContent = pairlistSummary(payload.preview);\n"
    "    pairlistAudit.textContent = payload.audit_event;\n"
    "  };\n"
    "  pairlistApplyButton.onclick = async () => {\n"
    "    const payload = await postPairlist('/api/v1/pairlist/apply');\n"
    "    pairlistPreview.textContent = pairlistSummary(payload.preview);\n"
    "    pairlistAudit.textContent = payload.audit_event;\n"
    "  };\n"
    "}\n"
    "</script>\n"
)
