from __future__ import annotations

from enum import StrEnum, unique


@unique
class ConfigErrorCode(StrEnum):
    CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
    CONFIG_VALIDATION_FAILED = "CONFIG_VALIDATION_FAILED"
    EXCHANGE_MARGIN_MODE_UNSUPPORTED = "EXCHANGE_MARGIN_MODE_UNSUPPORTED"
    EXCHANGE_TRADING_MODE_UNSUPPORTED = "EXCHANGE_TRADING_MODE_UNSUPPORTED"
    EXCHANGE_UNSUPPORTED = "EXCHANGE_UNSUPPORTED"
    FUTURES_MARGIN_MODE_REQUIRED = "FUTURES_MARGIN_MODE_REQUIRED"
    LIVE_TRADING_REQUIRES_CONFIRMATION = "LIVE_TRADING_REQUIRES_CONFIRMATION"
    MISSING_EXCHANGE_KEY = "MISSING_EXCHANGE_KEY"
    SPOT_MARGIN_MODE_NOT_ALLOWED = "SPOT_MARGIN_MODE_NOT_ALLOWED"
    YAML_NOT_MAPPING = "YAML_NOT_MAPPING"


@unique
class LogLevel(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


@unique
class Locale(StrEnum):
    EN = "en"
    KO = "ko"
    EL = "el"


@unique
class RiskProfileName(StrEnum):
    SAFE = "safe"
    BALANCED = "balanced"
    EXPERT = "expert"
